"""Add enable_receipt_print to settings

Revision ID: 02e743fabf9e
Revises: bcb72226cb89
Create Date: 2026-03-10 00:40:28.909198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e743fabf9e'
down_revision: Union[str, None] = 'bcb72226cb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_settings', sa.Column('enable_receipt_print', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_settings', 'enable_receipt_print')
    # ### end Alembic commands ###
