"""add_payment_split_fields

Revision ID: a1ecb5ff7e53
Revises: 53b27f7a410a
Create Date: 2026-03-03 09:01:37.768213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ecb5ff7e53'
down_revision: Union[str, None] = '53b27f7a410a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('momo_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('cash_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales', sa.Column('momo_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'momo_amount')
    op.drop_column('sales', 'cash_amount')
    op.drop_column('sales', 'momo_transaction_id')
    # ### end Alembic commands ###
