"""add_credits_table

Revision ID: b51818ba4af0
Revises: a1ecb5ff7e53
Create Date: 2026-03-03 09:31:18.684162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51818ba4af0'
down_revision: Union[str, None] = 'a1ecb5ff7e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creditor_name', sa.String(length=200), nullable=False),
    sa.Column('items_description', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_created_at'), 'credits', ['created_at'], unique=False)
    op.create_index(op.f('ix_credits_creditor_name'), 'credits', ['creditor_name'], unique=False)
    op.create_index(op.f('ix_credits_id'), 'credits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credits_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_creditor_name'), table_name='credits')
    op.drop_index(op.f('ix_credits_created_at'), table_name='credits')
    op.drop_table('credits')
    # ### end Alembic commands ###
