"""add tax_amount

Revision ID: e1a635e3ef78
Revises: 6166b13b367f
Create Date: 2026-03-06 02:10:12.911757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a635e3ef78'
down_revision: Union[str, None] = '6166b13b367f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.add_column('sales', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'tax_amount')
    op.drop_column('credits', 'tax_amount')
    # ### end Alembic commands ###
